### PR TITLE
CORS configuration and disable playground

### PR DESCRIPTION
**Pull request by JacobPozaic**
- Added configuration to set Access-Control-Allow-Origin header value on responses.
- Added configuration to disable serving the playground webpage.

### CODE REVIEW

**Comment by hrj** [comment]
Hi @JacobPozaic, Thanks for the contrib. Will be happy to merge once the checks pass.

The error in CI was this:
```

Error: Exception in thread "main" org.json4s.package$MappingException: Did not find value which can be converted into boolean
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.Extraction$.$anonfun$convert$2(Extraction.scala:735)
	at scala.Option.getOrElse(Option.scala:201)
	at org.json4s.Extraction$.convert(Extraction.scala:735)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:410)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:637)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:189)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:188)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:342)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:637)
	at org.json4s.Extraction$.extract(Extraction.scala:408)
	at org.json4s.Extraction$.extract(Extraction.scala:40)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at lc.core.Config.<init>(config.scala:48)
	at lc.LCFramework$.main(Main.scala:14)
	at lc.LCFramework.main(Main.scala)
```

Note that we do this just before running the locust tests:
```
cp tests/debug-config.json data/config.json
```

I think you need to add the new config options in `tests/debug-config.json`

**Comment by JacobPozaic** [comment]
Test should pass now I think

**Comment by hrj** [comment]
Yes, it's passing! Please sign the DCO as per these instructions:
https://github.com/librecaptcha/lc-core/pull/101/checks?check_run_id=4448790832

**Comment by JacobPozaic** [comment]
@hrj I cant seem to get that DCO thing to pass.  I've tried a few times following the instructions and trying to clone a few different ways,  Any ideas on how to rectify this?

**Comment by hrj** [comment]
@JacobPozaic Thanks for your patience with this one! I think you shouldn't `merge` with origin/master, but rather `rebase` to origin/master. When you rebase, your commits will be "replayed" on top of the master branch.

Try this: `git rebase origin/master`. Now `git log` should show only your commits on top.
After that, force push the branch. And then follow the DCO instructions. (Just copy pasting them should work)

**Pull request closed without merging**
